packages:
  # the root package.json
  - '.'
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - 'example'
  # exclude packages that are inside test/ directories
  - '!**/test/**'
